from functools import reduce

"""
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms.  By starting with 1 and 2,
 the first 10 terms will be
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89 ....

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of
the even-valued terms.

"""


def fibo_even_nums(exceed_value: int):
    a, b = 0, 1
    keep_going = True
    while keep_going:
        if a > exceed_value:
            break

        if not a % 2:
            yield a

        a, b = b, a + b


def main():
    fib = fibo_even_nums(4000000)
    answer = 0
    for n in fib:
        answer += n
    print(answer)


if __name__ == '__main__':
    main()
